# Generated by Django 3.1.6 on 2021-02-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_turnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='date',
            field=models.DateTimeField(verbose_name='fecha'),
        ),
    ]
