# Generated by Django 3.1.6 on 2021-02-17 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 2, 17, 15, 24, 8, 900194), verbose_name='time'),
        ),
    ]
