# Generated by Django 3.1.6 on 2021-02-17 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_turnos', '0002_turno_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 2, 17, 15, 27, 39, 232397), verbose_name='time'),
        ),
    ]
