# Generated by Django 3.1.6 on 2021-02-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_turnos', '0003_turno_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
    ]
