# Generated by Django 3.1.6 on 2021-02-17 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_turnos', '0003_auto_20210217_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 2, 17, 15, 38, 25, 611039), verbose_name='time'),
        ),
    ]
