# Generated by Django 3.1.6 on 2021-02-17 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_turnos', '0004_auto_20210217_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 2, 17, 15, 42, 53, 218027), verbose_name='time'),
        ),
    ]
