# Generated by Django 3.1.6 on 2021-02-17 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_turnos', '0005_auto_20210217_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 2, 17, 15, 43, 14, 813382), verbose_name='time'),
        ),
    ]
