# Generated by Django 3.1.6 on 2021-02-17 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_turnos', '0007_auto_20210217_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 2, 17, 16, 17, 30, 231367), verbose_name='time'),
        ),
    ]
