# Generated by Django 3.1.6 on 2021-02-18 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_turnos', '0010_auto_20210217_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='time',
            field=models.TimeField(choices=[(1, '8:00'), (2, '9:00'), (3, '10:00'), (4, '11:00'), (5, '17:00'), (6, '18:00'), (7, '19:00')], default=datetime.datetime(2021, 2, 18, 3, 49, 58, 97338), verbose_name='time'),
        ),
    ]
