# Generated by Django 3.1.6 on 2021-02-18 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_turnos', '0011_auto_20210218_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='time',
            field=models.TimeField(choices=[('08:00:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00')], default=datetime.datetime(2021, 2, 18, 3, 59, 29, 930344), verbose_name='time'),
        ),
    ]
