# Generated by Django 3.1.6 on 2021-03-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0003_noticia_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='bloqueado',
            field=models.BooleanField(default=False),
        ),
    ]
